"""Pathway enrichment analysis for CKD candidate biomarkers.

Inputs are generated by the previous traditional, ML, and cell-type biomarker
pipelines. This script submits gene lists to Enrichr, saves enrichment tables,
and creates thesis-ready summary plots.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import requests
import seaborn as sns


ENRICHR_URL = "https://maayanlab.cloud/Enrichr"


LIBRARY_CANDIDATES = {
    "GO Biological Process": [
        "GO_Biological_Process_2026",
        "GO_Biological_Process_2025",
        "GO_Biological_Process_2023",
        "GO_Biological_Process_2021",
    ],
    "KEGG": [
        "KEGG_2026",
        "KEGG_2021_Human",
        "KEGG_2019_Human",
    ],
    "Reactome": [
        "Reactome_Pathways_2024",
        "Reactome_2022",
    ],
    "WikiPathways": [
        "WikiPathways_2024_Human",
        "WikiPathway_2023_Human",
        "WikiPathway_2021_Human",
        "WikiPathways_2019_Human",
    ],
    "MSigDB Hallmark": [
        "MSigDB_Hallmark_2020",
    ],
}


@dataclass(frozen=True)
class GeneSetSpec:
    name: str
    label: str
    source: Path
    max_genes: int
    sort_column: str
    ascending: bool = False


GENE_SET_SPECS = [
    GeneSetSpec(
        name="whole_consensus_ml_rf",
        label="Whole Dataset Consensus ML RF",
        source=Path("Using ML/results/consensus_traditional_ml_rf_biomarkers.csv"),
        max_genes=150,
        sort_column="consensus_score",
    ),
    GeneSetSpec(
        name="whole_ckd_up_traditional",
        label="Whole Dataset CKD Up Traditional",
        source=Path("results/ckd_upregulated_candidate_biomarkers.csv"),
        max_genes=200,
        sort_column="combined_biomarker_score",
    ),
    GeneSetSpec(
        name="whole_ckd_down_traditional",
        label="Whole Dataset CKD Down Traditional",
        source=Path("results/ckd_downregulated_reference_loss_genes.csv"),
        max_genes=200,
        sort_column="combined_biomarker_score",
    ),
    GeneSetSpec(
        name="epithelial_consensus",
        label="Epithelial Cells Consensus",
        source=Path("Cell Type Biomrker/results/epithelial_cells_consensus_traditional_ml_rf.csv"),
        max_genes=150,
        sort_column="consensus_score",
    ),
    GeneSetSpec(
        name="immune_consensus",
        label="Immune Cells Consensus",
        source=Path("Cell Type Biomrker/results/immune_cells_consensus_traditional_ml_rf.csv"),
        max_genes=150,
        sort_column="consensus_score",
    ),
    GeneSetSpec(
        name="endothelial_consensus",
        label="Endothelial Cells Consensus",
        source=Path("Cell Type Biomrker/results/endothelial_cells_consensus_traditional_ml_rf.csv"),
        max_genes=150,
        sort_column="consensus_score",
    ),
    GeneSetSpec(
        name="stroma_consensus",
        label="Stroma Cells Consensus",
        source=Path("Cell Type Biomrker/results/stroma_cells_consensus_traditional_ml_rf.csv"),
        max_genes=150,
        sort_column="consensus_score",
    ),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run pathway enrichment for CKD biomarker gene lists.")
    parser.add_argument("--output-dir", default="Pathway Enrichment")
    parser.add_argument("--min-overlap", type=int, default=2)
    parser.add_argument("--significance", type=float, default=0.05)
    parser.add_argument("--timeout", type=int, default=60)
    return parser.parse_args()


def safe_name(text: str) -> str:
    text = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_")
    return text.lower()


def clean_gene(value: object) -> str | None:
    if pd.isna(value):
        return None
    gene = str(value).strip()
    if not gene or gene.lower() == "nan":
        return None
    return gene


def unique_keep_order(values: Iterable[str]) -> list[str]:
    seen = set()
    out = []
    for value in values:
        if value not in seen:
            out.append(value)
            seen.add(value)
    return out


def read_gene_set(root: Path, spec: GeneSetSpec) -> tuple[pd.DataFrame, list[str]]:
    path = root / spec.source
    if not path.exists():
        raise FileNotFoundError(f"Missing input file: {path}")
    df = pd.read_csv(path)
    if "gene" not in df.columns:
        raise ValueError(f"Input file has no 'gene' column: {path}")

    if spec.sort_column in df.columns:
        df = df.sort_values(spec.sort_column, ascending=spec.ascending, kind="mergesort")

    genes = [g for g in (clean_gene(x) for x in df["gene"]) if g]
    genes = unique_keep_order(genes)[: spec.max_genes]
    if len(genes) < 3:
        raise ValueError(f"Too few genes for enrichment in {spec.name}: {len(genes)}")

    selected = pd.DataFrame(
        {
            "gene_set": spec.name,
            "gene_set_label": spec.label,
            "source_file": str(spec.source),
            "gene_rank": range(1, len(genes) + 1),
            "gene": genes,
        }
    )
    return selected, genes


def available_enrichr_libraries(timeout: int) -> set[str]:
    response = requests.get(f"{ENRICHR_URL}/datasetStatistics", timeout=timeout)
    response.raise_for_status()
    payload = response.json()
    return {item["libraryName"] for item in payload["statistics"]}


def resolve_libraries(timeout: int) -> dict[str, str]:
    available = available_enrichr_libraries(timeout)
    resolved: dict[str, str] = {}
    for short_name, candidates in LIBRARY_CANDIDATES.items():
        for candidate in candidates:
            if candidate in available:
                resolved[short_name] = candidate
                break
        if short_name not in resolved:
            raise RuntimeError(f"No Enrichr library found for {short_name}. Tried: {candidates}")
    return resolved


def submit_gene_list(genes: list[str], description: str, timeout: int) -> int:
    files = {
        "list": (None, "\n".join(genes)),
        "description": (None, description),
    }
    response = requests.post(f"{ENRICHR_URL}/addList", files=files, timeout=timeout)
    response.raise_for_status()
    payload = response.json()
    return int(payload["userListId"])


def fetch_enrichment(user_list_id: int, library: str, timeout: int) -> pd.DataFrame:
    response = requests.get(
        f"{ENRICHR_URL}/enrich",
        params={"userListId": user_list_id, "backgroundType": library},
        timeout=timeout,
    )
    response.raise_for_status()
    data = response.json().get(library, [])
    rows = []
    for item in data:
        overlap = item[5]
        if isinstance(overlap, str):
            overlap_genes = [g.strip() for g in overlap.split(";") if g.strip()]
        else:
            overlap_genes = [str(g).strip() for g in overlap if str(g).strip()]
        rows.append(
            {
                "rank": item[0],
                "term": item[1],
                "p_value": item[2],
                "z_score": item[3],
                "combined_score": item[4],
                "overlap_genes": ";".join(overlap_genes),
                "overlap_n": len(overlap_genes),
                "adjusted_p_value": item[6],
                "old_p_value": item[7] if len(item) > 7 else np.nan,
                "old_adjusted_p_value": item[8] if len(item) > 8 else np.nan,
            }
        )
    return pd.DataFrame(rows)


def neg_log10(values: pd.Series | np.ndarray) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    arr = np.clip(arr, 1e-300, 1.0)
    return -np.log10(arr)


def wrap_term(term: str, width: int = 58) -> str:
    term = re.sub(r"\s+", " ", str(term)).strip()
    return "\n".join(textwrap.wrap(term, width=width, break_long_words=False))


def save_top_terms_plot(df: pd.DataFrame, gene_set: str, label: str, figdir: Path, top_n: int = 20) -> None:
    if df.empty:
        return
    plot_df = df.sort_values(["adjusted_p_value", "p_value", "rank"], kind="mergesort").head(top_n).copy()
    plot_df = plot_df.iloc[::-1].copy()
    plot_df["score"] = neg_log10(plot_df["adjusted_p_value"])
    plot_df["label"] = plot_df["term"].map(wrap_term)

    palette = {
        "GO Biological Process": "#2f6f8f",
        "KEGG": "#b24a3b",
        "Reactome": "#6f8f3a",
        "WikiPathways": "#8060a8",
        "MSigDB Hallmark": "#c48a2c",
    }

    fig_height = max(6.0, 0.45 * len(plot_df) + 1.2)
    fig, ax = plt.subplots(figsize=(11.5, fig_height))
    y = np.arange(len(plot_df))
    colors = [palette.get(x, "#666666") for x in plot_df["library_short"]]
    sizes = 45 + plot_df["overlap_n"].clip(upper=20) * 18
    ax.scatter(plot_df["score"], y, s=sizes, c=colors, alpha=0.88, edgecolor="white", linewidth=0.8)
    ax.set_yticks(y)
    ax.set_yticklabels(plot_df["label"], fontsize=8)
    ax.set_xlabel("-log10 adjusted p-value")
    ax.set_title(f"Top enriched pathways: {label}")
    ax.grid(axis="x", alpha=0.25)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    handles = []
    for lib, color in palette.items():
        if lib in set(plot_df["library_short"]):
            handles.append(plt.Line2D([0], [0], marker="o", color="w", label=lib, markerfacecolor=color, markersize=8))
    ax.legend(handles=handles, loc="lower right", frameon=False, fontsize=8)

    fig.tight_layout()
    fig.savefig(figdir / f"{gene_set}_top_enriched_terms.png", dpi=220)
    plt.close(fig)


def save_library_dotplot(df: pd.DataFrame, gene_set: str, label: str, figdir: Path, top_per_library: int = 8) -> None:
    if df.empty:
        return
    pieces = []
    for library_short, sub in df.groupby("library_short", sort=False):
        pieces.append(sub.sort_values(["adjusted_p_value", "p_value"]).head(top_per_library))
    plot_df = pd.concat(pieces, ignore_index=True)
    plot_df = plot_df.sort_values(["library_short", "adjusted_p_value"], ascending=[True, False]).copy()
    plot_df["score"] = neg_log10(plot_df["adjusted_p_value"])
    plot_df["label"] = plot_df.apply(lambda r: f"{r['library_short']}: {wrap_term(r['term'], 45)}", axis=1)

    fig_height = max(7.0, 0.36 * len(plot_df) + 1.5)
    fig, ax = plt.subplots(figsize=(12, fig_height))
    y = np.arange(len(plot_df))
    sns.scatterplot(
        data=plot_df,
        x="score",
        y=y,
        hue="library_short",
        size="overlap_n",
        sizes=(50, 260),
        alpha=0.88,
        ax=ax,
        palette="Set2",
        edgecolor="white",
        linewidth=0.7,
    )
    ax.set_yticks(y)
    ax.set_yticklabels(plot_df["label"], fontsize=7)
    ax.set_xlabel("-log10 adjusted p-value")
    ax.set_ylabel("")
    ax.set_title(f"Library-wise enriched terms: {label}")
    ax.grid(axis="x", alpha=0.25)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.legend(loc="lower right", frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(figdir / f"{gene_set}_library_dotplot.png", dpi=220)
    plt.close(fig)


def save_significant_count_heatmap(df: pd.DataFrame, figdir: Path, significance: float) -> None:
    if df.empty:
        return
    counts = (
        df.assign(significant=df["adjusted_p_value"] < significance)
        .groupby(["gene_set_label", "library_short"], observed=False)["significant"]
        .sum()
        .reset_index()
    )
    matrix = counts.pivot(index="gene_set_label", columns="library_short", values="significant").fillna(0)
    matrix = matrix.reindex(columns=[x for x in LIBRARY_CANDIDATES if x in matrix.columns])

    fig, ax = plt.subplots(figsize=(10.5, max(4.5, 0.45 * len(matrix) + 1.5)))
    sns.heatmap(matrix, annot=True, fmt=".0f", cmap="YlGnBu", linewidths=0.4, linecolor="white", cbar_kws={"label": "Significant terms"}, ax=ax)
    ax.set_xlabel("")
    ax.set_ylabel("")
    ax.set_title(f"Number of enriched terms at FDR < {significance}")
    fig.tight_layout()
    fig.savefig(figdir / "enrichment_significant_term_counts.png", dpi=220)
    plt.close(fig)


def save_top_term_heatmap(df: pd.DataFrame, figdir: Path, top_terms: int = 35) -> None:
    if df.empty:
        return
    top = (
        df.sort_values(["adjusted_p_value", "p_value", "rank"])
        .drop_duplicates(["term"])
        .head(top_terms)["term"]
        .tolist()
    )
    sub = df[df["term"].isin(top)].copy()
    sub["score"] = neg_log10(sub["adjusted_p_value"])
    matrix = sub.pivot_table(index="term", columns="gene_set_label", values="score", aggfunc="max").fillna(0)
    matrix = matrix.loc[top]
    labels = [wrap_term(x, 45) for x in matrix.index]

    fig, ax = plt.subplots(figsize=(11.5, max(8.5, 0.38 * len(matrix) + 1.5)))
    sns.heatmap(matrix, cmap="mako_r", linewidths=0.3, linecolor="white", cbar_kws={"label": "-log10 adjusted p-value"}, ax=ax)
    ax.set_yticklabels(labels, rotation=0, fontsize=7)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=35, ha="right", fontsize=8)
    ax.set_xlabel("")
    ax.set_ylabel("")
    ax.set_title("Shared and gene-set-specific enriched pathways")
    fig.tight_layout()
    fig.savefig(figdir / "combined_top_enriched_pathways_heatmap.png", dpi=220)
    plt.close(fig)


def save_summary_tables(all_results: pd.DataFrame, results_dir: Path, significance: float) -> None:
    if all_results.empty:
        return

    top_summary = (
        all_results.sort_values(["gene_set", "adjusted_p_value", "p_value", "rank"])
        .groupby(["gene_set", "gene_set_label", "library_short"], observed=False)
        .head(10)
        .reset_index(drop=True)
    )
    top_summary.to_csv(results_dir / "top10_terms_per_gene_set_and_library.csv", index=False)

    significant = all_results[all_results["adjusted_p_value"] < significance].copy()
    significant.to_csv(results_dir / "significant_enriched_terms_fdr_lt_0_05.csv", index=False)

    count_summary = (
        all_results.assign(significant=all_results["adjusted_p_value"] < significance)
        .groupby(["gene_set", "gene_set_label", "library_short"], observed=False)
        .agg(
            total_terms=("term", "count"),
            significant_terms=("significant", "sum"),
            best_adjusted_p_value=("adjusted_p_value", "min"),
            best_term=("term", lambda x: x.iloc[0] if len(x) else ""),
        )
        .reset_index()
    )
    count_summary.to_csv(results_dir / "enrichment_count_summary.csv", index=False)


def main() -> None:
    args = parse_args()
    root = Path.cwd()
    output_dir = root / args.output_dir
    results_dir = output_dir / "results"
    figures_dir = output_dir / "figures"
    logs_dir = output_dir / "logs"
    for directory in [results_dir, figures_dir, logs_dir]:
        directory.mkdir(parents=True, exist_ok=True)

    gene_set_frames = []
    gene_sets: dict[str, tuple[str, list[str]]] = {}
    for spec in GENE_SET_SPECS:
        frame, genes = read_gene_set(root, spec)
        gene_set_frames.append(frame)
        gene_sets[spec.name] = (spec.label, genes)

    input_gene_sets = pd.concat(gene_set_frames, ignore_index=True)
    input_gene_sets.to_csv(results_dir / "input_gene_sets.csv", index=False)

    gene_set_summary = (
        input_gene_sets.groupby(["gene_set", "gene_set_label", "source_file"], observed=False)
        .agg(
            n_genes=("gene", "count"),
            top_15_genes=("gene", lambda x: ", ".join(x.head(15))),
        )
        .reset_index()
    )
    gene_set_summary.to_csv(results_dir / "input_gene_set_summary.csv", index=False)

    libraries = resolve_libraries(args.timeout)
    with open(logs_dir / "resolved_enrichr_libraries.json", "w", encoding="utf-8") as handle:
        json.dump(libraries, handle, indent=2)

    all_frames = []
    for gene_set, (label, genes) in gene_sets.items():
        user_list_id = submit_gene_list(genes, label, args.timeout)
        for library_short, library_name in libraries.items():
            print(f"Running {gene_set} against {library_name}...")
            enriched = fetch_enrichment(user_list_id, library_name, args.timeout)
            if enriched.empty:
                continue
            enriched.insert(0, "gene_set", gene_set)
            enriched.insert(1, "gene_set_label", label)
            enriched.insert(2, "library_short", library_short)
            enriched.insert(3, "library_name", library_name)
            enriched = enriched[enriched["overlap_n"] >= args.min_overlap].copy()
            enriched["neg_log10_adjusted_p_value"] = neg_log10(enriched["adjusted_p_value"])
            enriched["gene_list_size"] = len(genes)
            out_path = results_dir / f"{gene_set}__{safe_name(library_short)}.csv"
            enriched.to_csv(out_path, index=False)
            all_frames.append(enriched)

    if not all_frames:
        raise RuntimeError("No enrichment results were returned.")

    all_results = pd.concat(all_frames, ignore_index=True)
    all_results = all_results.sort_values(["gene_set", "adjusted_p_value", "p_value", "rank"], kind="mergesort")
    all_results.to_csv(results_dir / "all_enrichment_results.csv", index=False)

    save_summary_tables(all_results, results_dir, args.significance)
    save_significant_count_heatmap(all_results, figures_dir, args.significance)
    save_top_term_heatmap(all_results, figures_dir)

    for gene_set, (label, _) in gene_sets.items():
        sub = all_results[all_results["gene_set"] == gene_set].copy()
        save_top_terms_plot(sub, gene_set, label, figures_dir)
        save_library_dotplot(sub, gene_set, label, figures_dir)

    print("\nPathway enrichment complete.")
    print(f"Results: {results_dir}")
    print(f"Figures: {figures_dir}")
    print("\nInput gene sets:")
    print(gene_set_summary.to_string(index=False))

    top = pd.read_csv(results_dir / "top10_terms_per_gene_set_and_library.csv")
    print("\nBest term per gene set/library:")
    best = top.sort_values(["gene_set", "library_short", "adjusted_p_value"]).groupby(
        ["gene_set_label", "library_short"], observed=False
    ).head(1)
    print(best[["gene_set_label", "library_short", "term", "adjusted_p_value", "overlap_n"]].to_string(index=False))


if __name__ == "__main__":
    main()
